// Generated by dts-bundle v0.7.3

export function crawling_(videoId: string, limit: number): Promise<any>;
export function crawlingCallback_(videoId: string, limit: number, callback: (arr: string[], end: boolean) => void): Promise<any>;
export function crawlingIterator_(videoId: string, limit: number): Promise<any>;
export const crawling: typeof crawling_;
export const crawlingCallback: typeof crawlingCallback_;
export const crawlingIterator: typeof crawlingIterator_;

